Algoritmo NumeroDoble
	//DECLARAMOS UNA VARIABLE PARA GUARDAR
	//EL NUMERO
	numero <- 0
	//PEDIMOS AL USUARIO UN VALOR PARA EL NUMERO
	Escribir "Introduzca un número"
	//ALMACENAMOS EL DATO QUE HA ESCRITO EL USUARIO
	Leer numero
	//DECLARAMOS UNA VARIABLE PARA ALMACENAR
	//LA OPERACION DE MULTIPLICAR POR DOS
	doble <- numero * 2
	//PINTAMOS EL RESULTADO POR PANTALLA
	Escribir doble
FinAlgoritmo
